import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',

      workbox: {
        // Phase B: modules are code-split, so the old 10 MB single-chunk cap
        // is no longer needed. 5 MB still covers the pdf.js worker chunk.
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      },

      // SINGLE SOURCE OF TRUTH for the web manifest. The plugin both writes
      // dist/manifest.webmanifest and injects the <link rel="manifest"> — so a
      // hand-written public/manifest.webmanifest is silently overwritten and a
      // hand-written <link> ends up duplicated. Edit the manifest HERE.
      //
      // The icons used to point at /vite.svg, which is not in public/ — the
      // manifest referenced a 404, so "Install app" had no icon to show.
      // They are now real PNGs, regenerated by `node scripts/gen-pwa-icons.cjs
      // public/icons`, including a maskable variant so Android does not crop
      // the truck into a circle.
      manifest: {
        id: '/',
        name: 'Prasad Transport ERP',
        short_name: 'Prasad ERP',
        description: 'Transport and logistics ERP — fleet operations, trip settlement, live tracking and the finance books.',
        // Matches the splash background so the status bar does not flash white.
        theme_color: '#020617',
        background_color: '#020617',
        display: 'standalone',
        orientation: 'any',
        start_url: '/',
        scope: '/',
        categories: ['business', 'productivity'],
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
        ]
      }
    })
  ],

  build: {
    // Keep heavy shared vendors in their own long-cacheable chunks so a code
    // change in one ERP module doesn't invalidate the framework/vendor cache.
    rollupOptions: {
      output: {
        manualChunks(id: string) {
          if (id.includes('node_modules')) {
            // No vendor-firebase chunk: the client SDK is gone from the app.
            if (id.includes('recharts') || id.includes('d3-')) return 'vendor-recharts';
            if (id.includes('quill')) return 'vendor-quill';
            if (id.includes('react')) return 'vendor-react';
          }
        },
      },
    },
  },
});
