import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',

      workbox: {
        // Phase B: modules are code-split, so the old 10 MB single-chunk cap
        // is no longer needed. 5 MB still covers the pdf.js worker chunk.
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        // Written out rather than trusted to defaults, because these three are
        // the whole difference between "deployed" and "on the screen":
        //   skipWaiting    — the new worker activates the moment it installs,
        //                    instead of idling behind the old one until every
        //                    tab closes (on an office machine: never).
        //   clientsClaim   — it takes over the already-open tabs, so the
        //                    reload in pwaUpdate.ts swaps them to the new build.
        //   cleanupOutdatedCaches — precaches from earlier deploys are deleted
        //                    on activation; an iPhone that has installed the
        //                    PWA does not accumulate every bundle ever shipped.
        skipWaiting: true,
        clientsClaim: true,
        cleanupOutdatedCaches: true,
      },

      // SINGLE SOURCE OF TRUTH for the web manifest. The plugin both writes
      // dist/manifest.webmanifest and injects the <link rel="manifest"> — so a
      // hand-written public/manifest.webmanifest is silently overwritten and a
      // hand-written <link> ends up duplicated. Edit the manifest HERE.
      //
      // The icons used to point at /vite.svg, which is not in public/ — the
      // manifest referenced a 404, so "Install app" had no icon to show.
      // They are now real PNGs, regenerated by `node scripts/gen-pwa-icons.cjs
      // public/icons`, including a maskable variant so Android does not crop
      // the truck into a circle.
      manifest: {
        id: '/',
        name: 'Prasad Transport ERP',
        short_name: 'Prasad ERP',
        description: 'Transport and logistics ERP — fleet operations, trip settlement, live tracking and the finance books.',
        // Matches the splash background so the status bar does not flash white.
        theme_color: '#0a1024',
        background_color: '#0a1024',
        display: 'standalone',
        orientation: 'any',
        start_url: '/',
        scope: '/',
        categories: ['business', 'productivity'],
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
        ]
      }
    })
  ],

  // Stamped into the bundle at build time. pwaUpdate.ts compares it against
  // what the device last ran and purges legacy caches when it changes — the
  // "did my phone actually get the new build" question, answerable in code.
  define: {
    __BUILD_STAMP__: JSON.stringify(new Date().toISOString()),
  },

  build: {
    // Keep heavy shared vendors in their own long-cacheable chunks so a code
    // change in one ERP module doesn't invalidate the framework/vendor cache.
    rollupOptions: {
      output: {
        // Vite hashes by default; written out so the cache-busting contract is
        // visible and cannot be lost to a future default change. A deploy that
        // changes one byte changes the filename, and index.html (served
        // no-cache) points at the new name — no client can hold a stale chunk.
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
        manualChunks(id: string) {
          if (id.includes('node_modules')) {
            // No vendor-firebase chunk: the client SDK is gone from the app.
            if (id.includes('recharts') || id.includes('d3-')) return 'vendor-recharts';
            if (id.includes('quill')) return 'vendor-quill';
            if (id.includes('react')) return 'vendor-react';
          }
        },
      },
    },
  },
});
